language: php
os: linux
dist: jammy
php:
  - 8.2
env:
  - PHP=8.2
before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
install:
  - composer install
script: vendor/bin/phpunit --configuration phpunit.xml
